### ISSUE TITLE
No longer works with Anki 2.1.36beta2

### ISSUE THREAD

**Issue by AnKingMed** [mankinence/ImageResizer#10]
https://forums.ankiweb.net/t/anki-2-1-36-beta/3893/13

This will produce an error when using ctrl+v in the add card dialog. The link above has a discussion on the error produced and where the code was changed so that you can make a quick update.

Thanks!

**Comment by searene** [comment]
@mattcarmody Hi, I've merged this pull request and modified it a little bit to make it work both in 2.1.36 and lower, could you have a check and upload it toAnkiWeb?

**Comment by searene** [comment]
Hi, @AnKingMed 

I've uploaded the working version to AnkiWeb, could you check if it's fixed?

**Comment by AnKingMed** [comment]
looks good to me! Thanks for the fix!

**Comment by searene** [comment]
Thanks for the verification!
