### ISSUE TITLE
Disables pasting without formatting

### ISSUE THREAD

**Issue by elliotsoomro** [mankinence/ImageResizer#12]
While recently downloading the add-on I realised that it disabled pasting text without formatting (Cmd+Shift+V) when creating notes. Had to disable the plugin, since this is a feature I use frequently. Maybe it is something to look into?

**Comment by searene** [comment]
@elliotsoomro You can try clicking on `Tools -> Image Resizer` on the menu bar to open the `Image Resizer` setting dialog, in it you will see a button called "Grab the shortcut", click on it press something else like `Cmd + v` to change the pasting shortcut.

I don't own a Mac, but you can try this method and check if it works.

**Comment by elliotsoomro** [comment]
Yes, that worked. Thanks for the quick reply!
