### ISSUE TITLE
Please do not disable SSL checking

### ISSUE THREAD

**Issue by dae** [mankinence/ImageResizer#20]
Disabling SSL checking throughout the app is potentially putting users at risk, and I wouldn't be surprised if this was also the cause of add-ons failing to update when this add-on is installed. Please remove the following code - I doubt you even need it in Anki 2.1:

https://github.com/mankinence/ImageResizer/blob/d2e6f6dce7b20599206af4ae05c899633d06cf57/2.1/__init__.py#L26

**Comment by searene** [comment]
Hi,
Thanks for reporting. The workaround has been removed and an updated addon has been uploaded.

**Comment by dae** [comment]
Thanks searene.
