### ISSUE TITLE
Sophos Endpoint security detecting Anki as Network Threat C2/Generic-A after 4/11/21 SSL update

### ISSUE THREAD

**Issue by fatherfauci** [mankinence/ImageResizer#21]
As the title says -- after the recent update on 4/11/21, Sophos Endpoint security detects a network threat C2/Generic-A possibly after enabling SSL. Any solutions for this issue?

**Comment by searene** [comment]
That's strange, enabling SSL should be a security enhancement. Does it happen to some specific images only or all the images?

**Comment by fatherfauci** [comment]
My apologies, please disregard. There was an issue with another add on (Anki Killstreaks) not this one.
