### ISSUE TITLE
Unable to paste text from another window

### ISSUE THREAD

**Issue by azziyyc** [mankinence/ImageResizer#26]
Sometimes, I copy text from a website and paste it into anki. However, recently it has caused anki to crash. I started enabling and disabling addons and it was the "image resizer" addon that had any effect when disabled.

**Comment by searene** [comment]
Could you provide more information? I want to know:
1. What's your Anki version?
2. Does the crash happen all the time, or does it only happen for some images and not others?

**Comment by azziyyc** [comment]
Hi,

My anki version is 2.1.44
The crash happened every time, and not for pasting images, but pasting text
that I have highlighted from another window. However, I must inform you
that the issue has stopped after having been prompted to update the addon,
restarting anki and re-enabling the addon. I'm not sure what was
causing the issue seeing as I was copying and pasting text and not images,
but the problem seems to have been resolved. Thanks for your correspondence.

**Comment by searene** [comment]
Glad it worked for you.
