### ISSUE TITLE
Not working with 2.1.50beta5

### ISSUE THREAD

**Issue by AnKingMed** [mankinence/ImageResizer#29]
I'm getting this error when I paste, even when the image resize on pasting is turned off

> Traceback (most recent call last):
>   File "aqt.webview", line 42, in cmd
>   File "aqt.webview", line 149, in _onCmd
>   File "aqt.webview", line 613, in _onBridgeCmd
>   File "aqt.editor", line 463, in onBridgeCmd
>   File "aqt.editor", line 924, in onPaste
>   File "aqt.editor", line 1183, in onPaste
>   File "aqt.editor", line 1177, in _onPaste
>   File "decorator", line 232, in fun
>   File "anki.hooks", line 89, in decorator_wrapper
>   File "anki.hooks", line 86, in repl
> TypeError: _processMime_around_with_extended() got multiple values for argument '_old'

**Comment by searene** [comment]
Hi @AnKingMed, Thanks for reporting! I think I've fixed it, could you update the addon and try again?

**Comment by AnKingMed** [comment]
Seems to be working great now!
