### ISSUE TITLE
anki 2.1.50 rc2 qt6 mac m1 arm error

### ISSUE THREAD

**Issue by yifan0414** [mankinence/ImageResizer#30]
<img src="https://picture-suyifan.oss-cn-shenzhen.aliyuncs.com//uPic/20220402sOEIcn.png" alt="20220402sOEIcn"/>

**Comment by searene** [comment]
ImageResizer doesn't support Qt 6 for now. There are many differences between Qt 5 and Qt 6.

**Comment by searene** [comment]
You can try using the Qt 5 version of Anki 2.1.50, it should work.
