### ISSUE TITLE
Bug: Enabling image resizer breaks Anki's audio download feature 🐛 

### ISSUE THREAD

**Issue by jhunschejones** [mankinence/ImageResizer#32]
### Bug overview:
Anki has a native feature that automatically downloads audio files when a URL pasted into a field ends with `.mp3`. With the Image Resizer add-on installed, the audio download feature no longer works. I attempted to set a custom keyboard shortcut for pasting images to be resized, but even with this set the add-on appears to be interfering with Anki's audio download functionality.

### Potential fix:
If there is a way to not intercept every paste event, or only the events that have to do with images, that might resolve this issue 🤔

**Comment by searene** [comment]
Hi @jhunschejones,

Sorry for the late reply, I've been pretty busy these days. I've fixed the issue by using the latest Anki hook. You need to update both ImageResizer and Anki to the latest version to make it work for you. Could you have a check and see if it works for you?

**Comment by jhunschejones** [comment]
Hi @searene 👋🏻  No worries at all, that was a much faster turn around-time than I expected 😁 

I gave it a shot on Anki desktop for OSX and both image pasting and audio pasting now work for me 🎉  I'll close out this issue as resolved, thanks for the fast fix!
